name: DVC Workflow

on:
  push:
    branches:
      - main

  schedule:
    - cron: "* 1 * * *"

jobs:
  dvc_operations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.5"

      - name: Install DVC
        run: |
          pip install dvc
          pip install dvc-gdrive
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up Google Cloud credentials
        run: |
          echo "${{ secrets.SECRETS_GOOGLE }}" > $HOME/.gcloud/service_account.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/.gcloud/service_account.json"

      - name: Configure DVC remote
        run: |
          dvc repro

      - name: Configure DVC push
        run: |
          dvc push

      - name: Configure DVC pull
        run: |
          dvc pull --force          
